repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^(.*/migrations/|.*/__pycache__/|manage\.py|.*\.pyc$)
        args: [--config=.flake8]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: ^(.*/migrations/|.*/__pycache__/|.*\.pyc$)
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^(.*/migrations/|.*/__pycache__/|.*\.pyc$)
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: ^(.*/migrations/|.*/__pycache__/|.*\.pyc$)
        args: [--remove-all-unused-imports, --in-place]
